AllCops:
  DisplayCopNames: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.bundle/**/*'
    - '.git/**/*'
    - '.vscode/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'public/**/*'
    - 'script/**/*'
  TargetRubyVersion: 2.5

Layout/AlignHash:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

# Align `when` with `case`.
Layout/CaseIndentation:
  Enabled: true

Layout/ClassStructure:
  Description: 'Enforces a configured order of definitions within a class body.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-classes'
  Enabled: true

Layout/ClosingHeredocIndentation:
  Enabled: false

# Align comments with method definitions.
Layout/CommentIndentation:
  Enabled: true

# No extra empty lines.
Layout/EmptyLines:
  Enabled: true

# Two spaces, no tabs (for indentation).
Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeFirstArg:
    Enabled: true

# Use `foo {}` not `foo{}`.
Layout/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

# Detect hard tabs, no hard tabs.
Layout/Tab:
  Enabled: true

Lint/Debugger:
  Enabled: true

# Annoying when used with some api that have blocks with sometimes useful parameters
Lint/UnusedBlockArgument:
  Enabled: true

# Annoying because it wines for &block parameters, which helps make signature more explicit
Lint/UnusedMethodArgument:
  Enabled: true

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Layout/TrailingWhitespace:
  Description: 'Avoid trailing whitespace.'
  StyleGuide: '#no-trailing-whitespace'
  Enabled: false
Metrics/AbcSize:
  Enabled: true

Metrics/BlockNesting:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  Max: 50
  ExcludedMethods: ['describe', 'context']

Metrics/ClassLength:
  Enabled: true
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/PerceivedComplexity:
  Enabled: true
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/CollectionMethods:
  Description: 'Preferred collection methods.'
  StyleGuide: '#map-find-select-reduce-size'
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/ReturnNil:
  Description: 'Use return instead of return nil.'
  Enabled: true

Style/StringMethods:
  Description: 'Checks if configured preferred methods are used over non-preferred.'
  Enabled: true

Style/StringLiterals:
  Enabled: false

# Defining a method with parameters needs parentheses.
Style/MethodDefParentheses:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

